baseURL = "http://localhost:1313/"
title = "Dancing in the Rain"
author = "Alex Carton"
paginate = 5

[params]
  orgName = "alexandrecarton"
  # orgLocal = "Localisation de votre organisation"
  #description = "Description du blog"
  favicon = "/img/logosite.png"  # Placez votre favicon dans static/img/
  logo = "/img/logosite.png"        # Placez votre logo dans static/img/
  sharing_image = "/img/partage.png"  # Image pour les partages sociaux
  twitter = "votre_twitter"  # Nom d'utilisateur Twitter sans @
  navallcaps = true  # Navigation en majuscules

  # Polices
  textFontFamily = "sans-serif"
  headingFontFamily = "serif"
  customtextFontFamily = "Helvetica Neue, Arial, sans-serif"
  customheadingFontFamily = "Georgia, Times New Roman, serif"

  # Thème de couleur
  theme = "forest"  # forest, grayscale, peach, plum, poppy, sky, violet, water

  # Icônes sociales
  socialInHeader = true
  socialInFooter = true

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fab"
    url = "https://www.linkedin.com/in/alexandre-carton-741146175/"

mainSections = ["blog", "project"]

[menu]
  [[menu.header]]
    name = "Blog"
    title = "Mes articles de blog"
    url = "/blog/"
    weight = 1
  [[menu.header]]
    name = "Projets"
    title = "Mes projets"
    url = "/project/"
    weight = 2
 
  [[menu.header]]
    name = "À propos"
    title = "À propos de nous"
    url = "/about/"
    weight = 3

  [[menu.footer]]
    name = "Mentions Légales"
    title = "Mentions Légales"
    url = "/legal/"
    weight = 1

  [[menu.footer]]
    name = "Politique de Confidentialité"
    title = "Politique de Confidentialité"
    url = "/privacy/"
    weight = 2





