baseURL = "https://alexandrecarton.netlify.app/"
title = "Alexandre CARTON"
author = "Alex Carton"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
paginate = 5
theme = "apero"


[params]
  orgName = "Alexandre Carton, France"
  # orgLocal = "France"
  #description = "Description du blog"
  favicon = "/img/logosite.png"  # Placez votre favicon dans static/img/
  logo = "/img/logosite.png"        # Placez votre logo dans static/img/
  sharing_image = "/img/logosite.png"  # Image pour les partages sociaux
  twitter = "votre_twitter"  # Nom d'utilisateur Twitter sans @
  navallcaps = true  # Navigation en majuscules

  # Polices
  # use an embedded font-family
  # serif options: Fraunces / EB Garamond / Bitter
  # sans-serif options: Commissioner / Atkinson Hyperlegible / Metropolis
  
  textFontFamily = "Commissioner"
  headingFontFamily = "Fraunces"
  customtextFontFamily = ""
  customheadingFontFamily = ""

  # Thème de couleur
  theme = "sky"  # forest, grayscale, peach, plum, poppy, sky, violet, water

  # Icônes sociales
  socialInHeader = true
  socialInFooter = true

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fab"
    url = "https://www.linkedin.com/in/alexandre-carton-741146175/"

mainSections = ["about", "blog", "project", "contact"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[menu]
  [[menu.header]]
    name = "Blog"
    title = "Mes articles de blog"
    url = "/blog/"
    weight = 2
  
  [[menu.header]]
    name = "Projets"
    title = "Mes projets"
    url = "/project/"
    weight = 3
  
  [[menu.header]]
    name = "Coaching"
    title = "Coaching"
    url = "/coaching/"
    weight = 5 

  [[menu.header]]
    name = "Contact"
    title = "Contact"
    url = "/contact/"
    weight = 5 
  
  [[menu.header]]
    name = "À propos"
    title = "À propos"
    url = "/about/"
    weight = 1



  [[menu.footer]]
    name = "Mentions Légales"
    title = "Mentions Légales"
    url = "/legal/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true






